language: de_trf_bertbasecased_lg
pipeline:
- name: WhitespaceTokenizer
  case-sensetive: false
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  entity_recognition: false
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: CRFEntityExtractor
  features:
  - - low
    - title
    - upper
  - - bias
    - low
    - prefix5
    - prefix2
    - suffix5
    - suffix3
    - suffix2
    - upper
    - title
    - digit
    - pattern
  - - low
    - title
    - upper
- name: DucklingHTTPExtractor
  url: http://34.107.51.226:8000
  dimensions:
  - duration
  - travel_days
  locale: de_DE
  timezone: Europe/Berlin
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MappingPolicy
- name: FormPolicy
- name: FallbackPolicy
  nlu_threshold: 0.3
  ambiguity_threshold: 0.1
  core_threshold: 0.3
  fallback_action_name: action_default_fallback
